//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;

namespace IdleMaster.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleMaster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f10\fbidi \fn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Changelog
        {
            get
            {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgBlacklist
        {
            get
            {
                object obj = ResourceManager.GetObject("imgBlacklist", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgDocument
        {
            get
            {
                object obj = ResourceManager.GetObject("imgDocument", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgExit
        {
            get
            {
                object obj = ResourceManager.GetObject("imgExit", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgFalse
        {
            get
            {
                object obj = ResourceManager.GetObject("imgFalse", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgGlobe
        {
            get
            {
                object obj = ResourceManager.GetObject("imgGlobe", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgInfo
        {
            get
            {
                object obj = ResourceManager.GetObject("imgInfo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgLock
        {
            get
            {
                object obj = ResourceManager.GetObject("imgLock", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgPause
        {
            get
            {
                object obj = ResourceManager.GetObject("imgPause", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgPauseSmall
        {
            get
            {
                object obj = ResourceManager.GetObject("imgPauseSmall", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgPlay
        {
            get
            {
                object obj = ResourceManager.GetObject("imgPlay", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgPlaySmall
        {
            get
            {
                object obj = ResourceManager.GetObject("imgPlaySmall", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgSettings
        {
            get
            {
                object obj = ResourceManager.GetObject("imgSettings", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgSkip
        {
            get
            {
                object obj = ResourceManager.GetObject("imgSkip", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgSkipSmall
        {
            get
            {
                object obj = ResourceManager.GetObject("imgSkipSmall", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgSpin
        {
            get
            {
                object obj = ResourceManager.GetObject("imgSpin", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgStatistics
        {
            get
            {
                object obj = ResourceManager.GetObject("imgStatistics", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgTrash
        {
            get
            {
                object obj = ResourceManager.GetObject("imgTrash", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgTrue
        {
            get
            {
                object obj = ResourceManager.GetObject("imgTrue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap imgView
        {
            get
            {
                object obj = ResourceManager.GetObject("imgView", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}